spring.application.name=springAIDemo

#spring.ai.ollama.chat.options.model=gemma3:12b
spring.ai.ollama.chat.options.model=gemma3:4b
#spring.ai.ollama.chat.options.model=deepseek-  r1:1.5b
#spring.ai.ollama.chat.options.model=gpt-oss:20b
#spring.ai.ollama.chat.options.model=llama3.2-vision:11b
#spring.ai.ollama.chat.options.model=qwen3:0.6b

#spring.ai.vectorstore.ollama.model=mxbai-embed-large
spring.ai.ollama.embedding.model=mxbai-embed-large

spring.data.redis.host=localhost
spring.data.redis.port=6379

#spring.ai.vectorstore.redis.host=localhost
#spring.ai.vectorstore.redis.port=6379
spring.ai.vectorstore.redis.initialize-schema=true
spring.ai.vectorstore.redis.index-name=my-index
spring.ai.vectorstore.redis.prefix=doc:

#spring.main.web-applicaiton-type=none

#spring.ai.mcp.server.enabled=true
#spring.ai.mcp.server.type=sse
#spring.ai.mcp.server.stdio.enabled=true
#spring.ai.mcp.server.name=IO Sessions MCP
#spring.ai.mcp.server.version=0.0.1
#
#spring.banner.enabled=false
#logging.level.org.springframework.ai.mcp.server.transport.stdio=OFF


